=== AMWA-TV/is-06/APIs/schemas/all.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "network-devices": { "$ref": "networkdevices.json" },
    "endpoints": { "$ref": "endpoints.json" },
    "network-links": { "$ref": "networklinks.json" },
    "endpoint-links": { "$ref": "endpointlinks.json" }
  },
  "required": [
    "network-devices",
    "endpoints",
    "network-links",
    "endpoint-links"
  ]
}

=== AMWA-TV/is-06/examples/topologyapi-v1.0-all-get-200.json
{
  "network-devices":
  [
      {
        "id": "8c:60:4f:04:24:41",
        "name":"switch1",
        "serial-number": "FXS1844Q1UH",
        "product-id": "N77-C7706",
        "product-description": "Nexus 7700 C7706 (6 Slot) Chassis",
        "vendor": "Cisco",
        "mac-address": "8c:60:4f:04:24:41",
        "mgmt-ip": "172.25.140.249",
        "version": "7.2(0)D1(1) [build 7.2(0)AV(0.89)]",
        "image-file": "N7700-s2-dk9.7.2.0.gbin",
        "build-time": "6/11/2015 10:00:00",
        "uptime": "x Days y hrs z mins a secs",
        "last-reset-reason": "reboot",
        "interfaces":
        [
          {
            "if-name": "eth 1/1",
            "admin-status": "up",
            "oper-status": "up",
            "down-reason": "NA",
            "built-in-mac-address":" 5cfc.666d.fa90",
            "mac-address": "8c:60:4f:04:21:41 (for L3, GW MAC) 5c:fc:66:6d:fa:90 (for L2, BIM) Modifiable manually",	
            "ip-address": "10.1.1.1",
            "operating-speed":"1G",
            "MTU": "1500",
            "mode": "trunk"
          }
        ] 
      },
      {
        "id":  "8c:60:4f:04:24:41",
        "name":"switch2",
        "serial-number": "FXS1844Q1UG",
        "product-id": "N77-C7706",
        "product-description": "Nexus 7700 C7706 (6 Slot) Chassis",
        "vendor": "Cisco",
        "mac-address": "8c:60:4f:04:24:41",
        "mgmt-ip": "172.25.140.249",
        "version": "7.2(0)D1(1) [build 7.2(0)AV(0.89)]",
        "image-file": "N7700-s2-dk9.7.2.0.gbin",
        "build-time": "6/11/2015 10:00:00",
        "uptime": "x Days y hrs z mins a secs",
        "last-reset-reason": "",
        "interfaces":
        [
          {
            "name": "eth 1/1",
            "admin-status": "up",
            "oper-status": "up",
            "down-reason": "NA",
            "built-in-mac-address":" 5c:fc:66:6d:fb:90",
            "mac-address": "8c:60:4f:04:22:41 (for L3, GW MAC) 5c:fc:66:6d:fa:90 (for L2, BIM) Modifiable manually",	
            "ip-address": "10.1.1.2",
            "operating-speed":"1G",
            "MTU": "1500",
            "mode": "trunk"
          },
          {
            "name": "eth 1/2",
            "status": "up",
            "down-reason": "NA",
            "built-in-mac-address":" 5cfc.666d.fb91",
            "mac-address": "8c:60:4f:04:22:42 (for L3, GW MAC) 5c:fc:66:6d:fa:90 (for L2, BIM) Modifiable manually",	
            "ip-address": "10.1.1.3",
            "operating-speed":"1G",
            "MTU": "1500",
            "mode": "trunk"
          }
        ] 
      }
  ],  
	
  "endpoints":
  [
      {
        "id":"9c:c6:4f:04:22:00", 
        "description":"user defined string",
        "chassis-id": "9c:c6:4f:04:22:00",
        "port-id": "9c:c6:4f:04:22:41"
      }
  ],  

  "network-links":
  [
      {
        "network-device-id": "8c:60:4f:04:24:41",
        "peer-network-device-id": "8c:60:4f:04:24:42",
        "network-interface": "eth 1/1",
        "peer-network-interface": "eth 1/1",
        "status": "up|down",
        "speed": "1G"
      }
 ],

 "endpoint-links":
 [
      {
        "network-device-id": "8c:60:4f:04:24:41",
        "endpoint-id": "9c:c6:4f:04:22:00",
        "network-interface": "eth 1/2",
        "endpoint-interface":"9c:c6:4f:04:22:41",
        "status": "up|down",
        "speed": "1G"
      }
  ]
}
