=== AMWA-TV/is-06/APIs/schemas/network-device.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "id",
    "chassis_id",
    "mgmt_ip",
    "interfaces"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the network device",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "label": {
      "description": "Freeform string label for the network device",
      "type": "string"
    },
    "chassis_id": {
      "type": "string",
      "description": "MAC address of the network device.",
      "pattern": "^([0-9A-Fa-f]{2}[-]){5}([0-9A-Fa-f]{2})$"
    },
    "mgmt_ip": {
      "type": "string",
      "description": "The management IP address of the network device.",
      "anyOf": [
        {
          "format": "ipv4"
        },
        {
          "format": "ipv6"
        }
      ]
    },
    "interfaces": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "port_id",
          "admin_status",
          "oper_status",
          "speed"
        ],
        "properties": {
          "port_id": {
            "description": "The ifAlias of the network device.",
            "type": "string"
          },
          "admin_status": {
            "description": "The administrative status of the interface.",
            "enum": [
              "up",
              "down"
            ]
          },
          "oper_status": {
            "description": "The operational status of the interface.",
            "enum": [
              "up",
              "down"
            ]
          },
          "speed": {
            "description": "The reported active speed of the interface.",
            "enum": [
              "100Mbit/s",
              "1Gbit/s",
              "10Gbit/s",
              "25Gbit/s",
              "40Gbit/s",
              "50Gbit/s",
              "100Gbit/s",
              "200Gbit/s",
              "400Gbit/s"
            ]
          },
          "mtu": {
            "description": "The MTU of the interface.",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== AMWA-TV/is-06/examples/netctrl-v1.0-network-device-id-get-200.json
{
  "id": "11b8973e-91c9-462d-8dad-6b37e53b3b9f",
  "label": "Network spine",
  "chassis_id": "41-B6-72-79-87-CC",
  "mgmt_ip": "10.10.10.16",
  "interfaces": [
    {
      "port_id": "Ethernet 1/1",
      "admin_status": "up",
      "oper_status": "up",
      "speed": "1Gbit/s",
      "mtu": 1500
    },
    {
      "port_id": "Ethernet 1/2",
      "admin_status": "up",
      "oper_status": "up",
      "speed": "100Gbit/s"
    },
    {
      "port_id": "Ethernet 1/3",
      "admin_status": "up",
      "oper_status": "up",
      "speed": "100Gbit/s"
    }
  ]
}

=== AMWA-TV/is-06/examples/netctrl-v1.0-network-devices-get-200.json
[
  {
    "id": "5482feef-49a2-4f3a-bf9c-d62b38a686c1",
    "label": "Network spine",
    "chassis_id": "55-C7-28-26-A2-48",
    "mgmt_ip": "10.10.16.16",
    "interfaces": [
      {
        "port_id": "Ethernet 1/1",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "1Gbit/s",
        "mtu": 1500
      },
      {
        "port_id": "Ethernet 1/2",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "100Gbit/s"
      },
      {
        "port_id": "Ethernet 1/3",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "100Gbit/s"
      }
    ]
  },
  {
    "id": "4b6452a8-6132-40e9-a8c3-aa0576e791f6",
    "label": "Network leaf 1",
    "chassis_id": "3A-4A-F9-30-14-61",
    "mgmt_ip": "10.10.18.18",
    "interfaces": [
      {
        "port_id": "Ethernet 1/1",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "1Gbit/s",
        "mtu": 1800
      },
      {
        "port_id": "Ethernet 1/2",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "10Gbit/s"
      },
      {
        "port_id": "Ethernet 1/3",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "10Gbit/s"
      }
    ]
  },
  {
    "id": "035a3ee6-1588-4ed3-a081-0a18539ad7d9",
    "label": "Network leaf 2",
    "chassis_id": "52-43-91-DF-0F-26",
    "mgmt_ip": "10.10.24.20",
    "interfaces": [
      {
        "port_id": "Ethernet 1/1",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "1Gbit/s",
        "mtu": 1800
      },
      {
        "port_id": "Ethernet 1/2",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "10Gbit/s"
      },
      {
        "port_id": "Ethernet 1/3",
        "admin_status": "up",
        "oper_status": "up",
        "speed": "10Gbit/s"
      }
    ]
  }
]
